name: assessment

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/app
      # - /usr/src/app/backend/node_modules
      # this line is for ignoring node_modules in the host machine and always use whatever in the container
      # this guarantees taht the node_modeules on the host machien willn't override the node_modules in the container
    image: api:fastapi # name of the image
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      - db
    
  db:
    image: postgres
    container_name: db
    env_file: db.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: