name: assessment

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/app
    image: api:fastapi # name of the image
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      - db
    
  db:
    image: postgres
    container_name: db
    env_file: db.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
